stages:
  - test
  - build

test:
  stage: test
  image: golang:1.23-bullseye
  script:
    - go test ./...

build:
  stage: build
  image: golang:1.23-bullseye
  variables:
    CGO_ENABLED: 0
  script:
    - cd cmd/tunnel-client
    - go build -ldflags "-X main.defaultServer=$DEFAULT_SERVER" -o tunnel-client-linux-amd64
    - GOOS=linux GOARCH=arm64 go build -ldflags "-X main.defaultServer=$DEFAULT_SERVER" -o tunnel-client-linux-arm64
    - GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.defaultServer=$DEFAULT_SERVER" -o tunnel-client-darwin-amd64
    - GOOS=darwin GOARCH=arm64 go build -ldflags "-X main.defaultServer=$DEFAULT_SERVER" -o tunnel-client-darwin-arm64
    - GOOS=windows GOARCH=amd64 go build -ldflags "-X main.defaultServer=$DEFAULT_SERVER" -o tunnel-client-amd64.exe
  artifacts:
    paths:
      - cmd/tunnel-client/tunnel-client-linux-amd64
      - cmd/tunnel-client/tunnel-client-linux-arm64
      - cmd/tunnel-client/tunnel-client-darwin-amd64
      - cmd/tunnel-client/tunnel-client-darwin-arm64
      - cmd/tunnel-client/tunnel-client-amd64.exe
